import turtle


turtle.tracer(0,0)
turtle.speed(10000)
#this bassicly just changes how dense the forests are, you can make it go wild if you change it above 7, 1-5 makes some cool changes
density = 4
#mountain drawings
#boundary 
outside=700
turtle.up()
turtle.goto(350,350)
turtle.down()
turtle.setheading(270)
for i in range(4):
   turtle.forward(outside)
   turtle.right(90)

#the big thing in the middle is supposed to be a lake, this changes the size of it, 134 is the best number for it
lakediamater=134
turtle.up()
turtle.goto(20,-58)
turtle.down()
turtle.dot(lakediamater)

def mountain1(x, y):
   turtle.up()
   turtle.goto(x, y)
   turtle.down()
   turtle.left(80)
   turtle.forward(10)
   turtle.right(5)
   turtle.forward(10)
   turtle.right(100)
   turtle.forward(3)
   turtle.left(100)
   turtle.forward(20)
   turtle.right(120)
   turtle.forward(5)
   turtle.left(120)
   turtle.forward(15)
   turtle.left(10)
   turtle.forward(10)
   turtle.right(150)
   turtle.forward(7)
   turtle.left(150)
   turtle.forward(20)
   turtle.right(160)
   
   turtle.forward(20)
   turtle.left(100)
   turtle.forward(4)
   turtle.right(110)
   turtle.forward(15)
   turtle.left(120)
   turtle.forward(7)
   turtle.right(110)
   turtle.forward(20) 
   turtle.left(150)
   turtle.forward(6)
   turtle.right(150)
   turtle.forward(30)
def mountain2():
   
   turtle.left(80)
   turtle.forward(7)
   turtle.right(2)
   turtle.forward(7)
   turtle.right(110)
   turtle.forward(4)
   turtle.left(110)
   turtle.forward(8)
   turtle.right(115)
   turtle.forward(4)
   turtle.left(120)
   turtle.forward(15)
   turtle.left(7)
   turtle.forward(9)
   turtle.right(145)
   turtle.forward(5)
   turtle.left(145)
   turtle.forward(9)
   turtle.right(160)


   turtle.forward(20)
   turtle.left(100)
   turtle.forward(4)
   turtle.right(110)
   turtle.forward(15)
   turtle.left(120)
   turtle.forward(7)
   turtle.right(110)
   turtle.forward(20)
   turtle.left(150)
   turtle.forward(6)
   turtle.right(150)
   turtle.forward(30)
def mountain3():
   
   turtle.right(80)
   turtle.forward(7)
   turtle.left(2)
   turtle.forward(7)
   turtle.left(110)
   turtle.forward(4)
   turtle.right(110)
   turtle.forward(8)
   turtle.left(115)
   turtle.forward(4)
   turtle.right(120)
   turtle.forward(15)
   turtle.right(7)
   turtle.forward(9)
   turtle.left(145)
   turtle.forward(5)
   turtle.right(145)
   turtle.forward(9)
   turtle.left(160)


   turtle.forward(20)
   turtle.right(100)
   turtle.forward(4)
   turtle.left(110)
   turtle.forward(15)
   turtle.right(120)
   turtle.forward(7)
   turtle.left(110)
   turtle.forward(20)
   turtle.right(150)
   turtle.forward(6)
   turtle.left(150)
   turtle.forward(30)
def keep(x, y):
   turtle.up()
   turtle.goto(x, y)
   turtle.down()
   turtle.forward(5)
   turtle.left(90)
   turtle.forward(7)
   turtle.left(90)
   turtle.forward(10)
   turtle.left(90)
   turtle.forward(4)
   #first pylong 
   turtle.right(90)
   turtle.forward(8)
   turtle.right(90)
   #middle 
   turtle.forward(4)
   turtle.left(90)
   turtle.forward(10)
   turtle.left(90)
   turtle.forward(7)
   #second pylon
   turtle.left(90)
   turtle.forward(5)
   turtle.right(90)
   turtle.forward(30)
   turtle.left(90)
   #right before door
   turtle.forward(7)
   turtle.left(90)

   
   turtle.forward(5)
   for i in range (180):
       turtle.right(1)
       turtle.forward(0.05)
    
   turtle.forward(5)
   #door
   turtle.left(90)
   turtle.forward(5)
   turtle.left(90)
   turtle.forward(30)
   turtle.left(90)
   turtle.forward(19)
   #finishing
def tree1():
   for i in range(360):
        turtle.forward(0.1)
        turtle.right(1)
def foresttool():
   #this will draw three groups of 4 trees
   for i in range(3):
    for e in range(4):
        turtle.down()
        tree1()
        turtle.left(90)
        turtle.up()
        turtle.forward((5*((e+density)/2))/1.29)
    turtle.up()
    turtle.forward(28)
def riverstraight():
   
   turtle.forward(26)
   turtle.up()
   turtle.left(90)
   turtle.forward(9)
   turtle.left(90)
   turtle.down()
   turtle.forward(25)
   turtle.up()
   turtle.left(90)
   turtle.forward(8)
   turtle.left(90)
   turtle.forward(25)
   turtle.down()
def riverturn():
   for i in range(90):
      turtle.forward(0.3)
      turtle.left(1)
   turtle.left(90)
   turtle.up()   
   turtle.forward(10)
   turtle.down()
   turtle.left(90)
   for i in range(90):
      turtle.forward(0.15)
      turtle.right(1)
   turtle.up()
   turtle.left(180)
   for i in range(90):
      turtle.left(1)
      turtle.forward(0.15)
   turtle.right(90)
   turtle.forward(10)
   turtle.down()
def mountaintool1():
    #all you need to start a chain with mountain
   turtle.setheading(90)
   turtle.up()
   turtle.forward(25)
   turtle.left(90)
   turtle.forward(10)
   turtle.down()
   turtle.setheading(0)
def mountaintool2():
   #use this for the first mountain in mountain 3
   turtle.setheading(180)
   turtle.up()
   turtle.forward(52)
   turtle.right(90)
   turtle.forward(20)
   turtle.down()
   turtle.setheading(180)
def mountaintool3():
   #after using mountain tool 2 use this to infinitly do the chain
   turtle.setheading(90)
   turtle.up()
   turtle.forward(25)
   turtle.right(90)
   turtle.forward(10)
   turtle.down()
   turtle.setheading(180)    
def tree2(x, y):
   turtle.up()
   turtle.goto(x, y)
   turtle.down()
   for i in range(360):
        turtle.forward(0.1)
        turtle.right(1)
def g():
   #im really tierd of writing this line of code
   turtle.setheading(0)
def signature(x, y):
   #check the top right
   turtle.up()
   turtle.goto(x, y)
   turtle.down()
   turtle.setheading(90)
   turtle.forward(10)
   turtle.right(140)
   turtle.forward(11.547)
   turtle.left(140)
   turtle.forward(10)
   g()
   turtle.forward(2)
   for i in range(180):
      turtle.forward(0.05)
      turtle.right(1)
   turtle.forward(2)
   turtle.left(135)
   turtle.forward(6.05)
def goto(x, y):
   #saves three lines of code
   turtle.up()
   turtle.goto(x, y)
   turtle.down()

g()
mountain1(43, 87)
mountaintool1()
mountain2()
mountaintool1()
mountain2()
g()
riverstraight()
riverturn()
turtle.setheading(90)
for i in range(2):
   riverstraight()
riverturn()
turtle.setheading(180)
for i in range(7):
   riverstraight()
riverturn()
turtle.setheading(270)
for i in range(8):
   riverstraight()
goto(-300, 300)

foresttool()
tree2(200, -100)
g()
mountain1(-200, 200)
for i in range(3):
   mountaintool1()
   mountain2()
g()
mountain1(-200,-200)
for i in range(2):
   mountaintool1()
   mountain2()
g()
keep(100,-234)
g()
keep(-200, 155)
g()
keep(100, 300)
g()
keep(-155, -256)
g()
mountain1(-100,0)
mountaintool2()
mountain3()
mountaintool3()
mountain3()

turtle.setheading(270)
for i in range(2):
   riverstraight()
riverturn()
g()
for i in range(7):
   riverstraight()
mountain1(200, -150)
g()
mountain1(245, -250)
tree2(-100, 155)
tree2(100, 256)
goto(-300, 15)
foresttool()
goto(-200, -245)
turtle.setheading(226)
foresttool()
tree2(-92, 291)
tree2(88, -120)
goto(150, 50)
foresttool()
tree2(200, 50)
tree2(175, 78)
g()
mountain1(150, -30)
mountaintool1()
mountain2()
tree2(300, 300)
g()
keep(250, 300)
g()
mountain1(-10, -300)
goto(200, -250)
foresttool()
goto(0, -150)
foresttool()
g()
mountain1(-290, 130)
goto(-100, -250)
foresttool()
goto(-250, -100)
foresttool()
g()
mountain1(-300, -250)
mountaintool2()
mountain3()
g()
mountain1(100, -100)
goto(100, -160)
turtle.setheading(234)
foresttool()
g()
mountain1(100, 200)
for i in range(2):
   mountaintool1()
   mountain2()
goto(-250, 100)
foresttool()
turtle.setheading(254)
goto(270, -20)
foresttool()
goto(-150, 120)
g()
foresttool()
goto(290, 100)
turtle.setheading(90)
foresttool()

signature(310, 310)
 
turtle.up()

turtle.goto(10000,1090)


turtle.update()


turtle.exitonclick()



 